name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.5"

      - name: Generate binary for Linux
        run: |
          make build

      - name: Verify binary
        run: |
          file ../bin/bin.so
          if ! file bin/bin.so | grep -q "ELF 64-bit LSB shared object"; then
            echo "Binary is not a Linux shared object"
            exit 1
          fi
          ldd ../bin/bin.so || true
          readelf -h ../bin/bin.so

      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-binary
          path: bin/bin.so

      - name: Run tests
        run: dart test
